global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # - aletrmanager:9093

rule_files:
  # - first_rules.yml
  # - second_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - tagrets: ['localhost:9090']
