
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: '📬 Alert Manager'
    label: '📬 Alert Manager'
  - title: '⚡ Breaking'
    label: '⚡ Breaking'
  - title: '🐛 Bug Fixes'
    label: '🐛 Bug Fixes'
  - title: '📖 Documentation'
    label: '📖 Documentation'
  - title: '🚀 Feature'
    label: '🚀 Feature'
  - title: '📊 Grafana'
    label: '📊 Grafana'
  - title: '⛩ Maintenance'
    label: '⛩ Maintenance'
  - title: '🔥 Prometheus'
    label: '🔥 Prometheus'
  - title: '⭐ Stable Release'
    label: '⭐ Stable Release'

version-resolver:
  major:
    labels:
      - '⭐ Stable Release'
  minor:
    labels:
      - '⚡ Breaking'
  patch:
    labels:
      - '🚀 Alert Manager'
      - '🐛 Bug Fixes'
      - '🆙 Dependencies'
      - '📖 Documentation'
      - '🚀 Feature'
      - '📊 Grafana'
      - '⛩ Maintenance'
      - '🔥 Prometheus'

exclude-labels:
  - '🏃 skip-changelog'
