apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./ConfigMap
  - ./Deployment
  - ./Service

images:
  - name: tempo
    newName: grafana/tempo
    newTag: c61b6785-amd64
