apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./ConfigMap
  - ./Deployment
  - ./PersistentVolumeClaim
  - ./Service

images:
  - name: grafana
    newName: grafana/grafana
    newTag: 8.3.3
