apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./ClusterRole
  - ./ClusterRoleBinding
  - ./Deployment
  - ./Service
  - ./ServiceAccount

images:
  - name: prometheus
    newName: prom/prometheus
    newTag: v2.32.1
