apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./ClusterRole
  - ./ClusterRoleBinding
  - ./ConfigMap
  - ./Deployment
  - ./ServiceAccount
  - ./Namespace
images:
  - name: prometheus
    newName: quay.io/prometheus/prometheus
    newTag: v2.0.0
