apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./ConfigMap
  - ./Deployment
images:
  - name: alertmanager
    newName: prom/alertmanager
    newTag: v0.21.0
