apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: alertmanager-config
    files:
      - config.yml
  - name: alertmanager-templates
    files:
      - default.tmpl
      - slack.tmpl
