apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./Deployment
  - ./Service
images:
  - name: grafana
    newName: grafana/grafana
    newTag: 7.5.2
