apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6831
      protocol: TCP
      targetPort: udp
  selector:
    app: tempo
  sessionAffinity: None
