apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  type: ClusterIP
  ports:
    - name: udp
      port: 6831
      protocol: UDP
      targetPort: udp
    - name: tempo
      port: 3100
      protocol: TCP
      targetPort: tempo
  selector:
    app: tempo
