name: Release

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  update-release-draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: ${{ contains(github.ref, 'refs/tags') }}

  update-changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install git-chglog
      - uses: KeisukeYamashita/setup-release@v1.0.2
        with:
          repository: git-chglog/git-chglog
      - name: Update changelog
        run: git-chglog --config .github/config.yml > CHANGELOG.md
      - name: Git Push
        run: |
          git add . \
            && git commit -m 'chore(docs): Update changelogs' \
            && git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
